// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var React = require("react");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");
var ReactTestingLibrary = require("bs-react-testing-library/src/ReactTestingLibrary.bs.js");
var UserEvent = require("@testing-library/user-event");
var Component1$ReactHooksTemplate = require("../Component1.bs.js");

function h_000(element) {
  return UserEvent.default.click(element);
}

function h_001(element) {
  return UserEvent.default.dblClick(element);
}

function h_002(element, strings) {
  return UserEvent.default.selectOptions(element, strings);
}

function h_003(element, text, options) {
  return UserEvent.default.type(element, text, {
              allAtOnce: Js_null_undefined.fromOption(options[/* allAtOnce */0]),
              delay: Js_null_undefined.fromOption(options[/* delay */1])
            });
}

var h = /* record */[
  h_000,
  h_001,
  h_002,
  h_003
];

Jest.test("", (function (param) {
        var res = ReactTestingLibrary.render(undefined, undefined, React.createElement(Component1$ReactHooksTemplate.make, { }));
        ReactTestingLibrary.getByText(/* `Str */[
              4153489,
              "toggle"
            ], undefined, res);
        var t = ReactTestingLibrary.getByText(/* `Str */[
              4153489,
              "message here"
            ], undefined, res);
        console.log(t);
        var s = ReactTestingLibrary.getByText(/* `Str */[
              4153489,
              "message here"
            ], undefined, res);
        console.log(s);
        return Jest.Expect[/* toBe */2](true, Jest.Expect[/* expect */0](true));
      }));

exports.h = h;
/*  Not a pure module */
