// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function Component1(Props) {
  var match = React.useState((function () {
          return true;
        }));
  var setIsVisible = match[1];
  return React.createElement(React.Fragment, {
              children: null
            }, match[0] ? React.createElement("div", undefined, "message here") : null, React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(setIsVisible, (function (prev) {
                                    return !prev;
                                  }));
                    })
                }, "toggle"));
}

var make = Component1;

exports.make = make;
/* react Not a pure module */
